# Generated by Django 3.2 on 2021-04-19 19:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='фото')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.CharField(max_length=50, verbose_name='')),
                ('is_mvp', models.BooleanField(default=False, verbose_name='Работник месяца')),
                ('hire_date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='дата приема на работу')),
            ],
        ),
    ]
